# Generated by Django 5.0.4 on 2024-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='token',
            field=models.TextField(max_length=1024),
        ),
    ]
